#!/usr/bin/python3

import os
from PIL import Image
from inky.auto import auto


PATH = os.path.dirname(__file__)

# Initialising the eInk display.
try:
    inky_display = auto(ask_user=True, verbose=True)
except TypeError:
    raise TypeError("You need to update the Inky library to >= v1.1.0")
try:
    inky_display.set_border(inky_display.WHITE)
except NotImplementedError:
    pass

# Interactive loop to set a chosen image.
while True:
    filename = input("Image filename: ")
    img = Image.open(os.path.join(PATH, filename))
    
    # TODO: Preserve the aspect ratio of the image by cropping 
    img = img.resize(inky_display.resolution)

    # Display the logo image
    inky_display.set_image(img)
    inky_display.show()

